services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=portable-npc
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgres/data
  web:
    build: .
    environment:
      - DJANGO_SECRET_KEY=django-insecure-d6ylr(z_&ndwxlhppx#yoq1o1q8b9#_64i5+3evy98&#=&7$3w
      - POSTGRES_DB=portable-npc
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - '8000:8000'
volumes:
  db:
    driver: local
