# Generated by Django 4.2.7 on 2023-11-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="email"),
        ),
    ]
